export enum EmailType {
    OTP_VERIFICATION = 'OTP_VERIFICATION',
    RESET_PASSWORD_OTP = 'RESET_PASSWORD_OTP',
    WELCOME_VERIFIED = 'WELCOME_VERIFIED',
    WELCOME_NOT_VERIFIED = 'WELCOME_NOT_VERIFIED',
    PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS'
}