export enum EmailType {
    OTP_VERIFICATION = 'OTP_VERIFICATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    WELCOME_VERIFIED = 'WELCOME_VERIFIED',
    WELCOME_NOT_VERIFIED = 'WELCOME_NOT_VERIFIED',
}